spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true

jwt:
  secret: goodlekkfekfosd@424fe4oj5ojofjsdifjhij3lkfjl3jlkrjldk1252f