spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test